### ISSUE TITLE
Publish on Bazel Central Registry (BCR) ?

### ISSUE THREAD

**Issue by hzeller** [google/fuzztest#1350]
Now that fuzztest is [MODULE.bazel-ified](https://github.com/google/fuzztest/commit/7b9676c0d116af3daa3a3fc7583c51001ae2e484), it would be wonderful to have it published on https://registry.bazel.build/ for easy integration in other projects.

**Comment by Mizux** [comment]
FYI there is `20241028.0` in BCR -> to close this issue ?
ref: https://registry.bazel.build/modules/fuzztest
