### ISSUE TITLE
googletest should not be a dev_dependency on the MODULE.bazel

### ISSUE THREAD

**Issue by dieortin** [google/fuzztest#1386]
Following the instructions on the [Quickstart with Bazel page](https://github.com/google/fuzztest/blob/main/doc/quickstart-bazel.md), users are told to add `"@com_google_fuzztest//fuzztest:fuzztest_gtest_main"` as a dependency to the `cc_test` rule. That target depends on `@com_google_googletest`, which is not available when `fuzztest` is not the root module, as it is marked as a `dev_dependency`. This causes builds to fail.

**Comment by lszekeres** [comment]
Thanks! Should be fixed with https://github.com/google/fuzztest/commit/394595fbd31d95e6f25b7c1a4d98b93886a36371.

**Comment by dieortin** [comment]
That's great, thank you! Will a new version be published to the BCR?
