### ISSUE TITLE
Wrong cmake version required in CMakeLists.txt

### ISSUE THREAD

**Issue by oblomgr1** [google/fuzztest#322]
In the quickstart-cmake.md you ask the reader to begin base CMakeLists.txt with:

cmake_minimum_required(VERSION 3.14)

Unfortunately some CMakeLists.txt requires higher cmake versions than that. At least 3.19 according to the [cmake documentation](https://cmake.org/cmake/help/latest/command/add_library.html) covering:
add_library(<name> INTERFACE)

An example is: fuzztest/grammar_codegen/CMakeLists.txt

The error is:
CMake Error at fuzztest/grammar_codegen/CMakeLists.txt:6 (add_library):
  add_library INTERFACE library requires no source arguments.

**Comment by Changochen** [comment]
Thanks for the report! We have updated the doc to use `3.19`. Please let us know if you have further question.
