### ISSUE TITLE
Attempt to turn off `-Wpsabi` causes unknown warning error.

### ISSUE THREAD

**Issue by markww** [google/fuzztest#34]
I'm currently trying to include `fuzztest` as a third party repository via `http_repository` in [my project](https://github.com/google-research/raksha). I'm encountering the following error:

```
Step #3 - "presubmit": external/fuzztest/fuzztest/internal/coverage.cc:120:34: error: unknown warning group '-Wpsabi', ignored [-Werror,-Wunknown-warning-option]
Step #3 - "presubmit": #pragma clang diagnostic ignored "-Wpsabi"
```

It seems that the attempt to turn off the irrelevant `-Wpsabi` warning in `coverage.cc` is causing an "unknown warning error" in my compiler. I'm going to turn off the `-Wunknown-warning-option` to work around this, but thought I'd let y'all know in case there's something you can do to suppress this issue.

**Comment by fniksic** [comment]
Thanks for reporting this. It seems that the warning was added in Clang 11, and you seem to be using an older version. The same thing happens in our GitHub actions builds, which use Clang 10, but there it only triggers a warning, not an error.

**Comment by markww** [comment]
It's only a warning for us too, but we strive to use `-Werror` to not miss important warnings. I've turned off `-Wunknown-warning-option` to avoid this for now.

**Comment by lszekeres** [comment]
Hey Mark, can you check if https://github.com/google/fuzztest/commit/4cecedbdd1906f17562b4807941e450764350332 solves it? Thanks!

**Comment by lszekeres** [comment]
Bumping up your fuzztest version should fix the issue. Please feel free to re-open if it didn't.
