### ISSUE TITLE
Macro conflict in `fuzztest/regexp.cc` on `NO_THREAD_SAFETY_ANALYSIS`

### ISSUE THREAD

**Issue by markww** [google/fuzztest#41]
While attempting to build `fuzztest`, I encountered the following (warning, upgraded to) error:

```
'NO_THREAD_SAFETY_ANALYSIS' macro redefined [-Werror,-Wmacro-redefined]
#define NO_THREAD_SAFETY_ANALYSIS \
         ^
external/com_googlesource_code_re2/util/util.h:39:9: note: previous definition is here
#define NO_THREAD_SAFETY_ANALYSIS
         ^
 1 error generated.
```

It looks like `re2` and `absl` both enable a macro called `NO_THREAD_SAFETY_ANALYSIS` with different definitions. `re2` is doing it with a `#ifndef` guard, while `absl` is unconditionally dropping it in.

It looks like this could possibly be solved by just making the `re2` headers be included before the `absl` headers, though that would be  a non-standard include order. The real fix may be to ask one or both of the upstream repos to change the name of their macro or at least `#undef` it when they're done with it. Alternatively, (though this would be ugly) they could be explicitly `#undef`ed between the inclusions in this file.

**Comment by fniksic** [comment]
Hi Mark. Did the [Abseil commit 
6acb60c](https://github.com/abseil/abseil-cpp/commit/6acb60c161f1203e6eca929b87f2041da7714bfe) fix the issue for you?

**Comment by lszekeres** [comment]
Bumping up your ABSL version like in https://github.com/google/fuzztest/commit/3ae17833f0607ae17029e968eacadc7b8d88ebb5 fixes the issue.
