### ISSUE TITLE
Byte Array Mutator failed on empty input

### ISSUE THREAD

**Issue by Jay-Waves** [google/fuzztest#928]
Byte mutation functions [FlipBit](https://github.com/google/fuzztest/blob/8f82f46e14cc2484ddecf6d55e46243923f9a036/centipede/byte_array_mutator.cc#L169), [SwapBytes](https://github.com/google/fuzztest/blob/8f82f46e14cc2484ddecf6d55e46243923f9a036/centipede/byte_array_mutator.cc#L179), [ChangeByte](https://github.com/google/fuzztest/blob/8f82f46e14cc2484ddecf6d55e46243923f9a036/centipede/byte_array_mutator.cc#L186) will fail on empty input &data. 

Is it as expected? iow, will Centipede take empty vector<uint8_t> as valid input? If this is not the case, perhaps the following should be added:

```cpp
bool ByteArrayMutator::SwapBytes(ByteArray& data) {
+  if (!data.size())
+    return false;
  size_t idx1 = rng_() % data.size();
  size_t idx2 = rng_() % data.size();
  std::swap(data[idx1], data[idx2]);
  return true;
}
```

**Comment by ussuri** [comment]
Thanks for the report. This code is expected to be retired and is not used by default anyway. Please don't use it.
