### ISSUE TITLE
Add bzlmod support for Bazel

### ISSUE THREAD

**Issue by chandlerc** [google/fuzztest#950]
Bazel builds are moving towards a new modules system instead of the workspace files:
https://bazel.build/external/module

Filing this to track any work needed to add a module file for this project. I'll link to it from the request to add this project to the Bazel central registry.

**Comment by wffurr** [comment]
I have a draft CL for this issue, but it's hung up on the riegeli dependency, which requires a very old version of protobuf.  I'm attempting to update riegeli to use a newer protobuf, but it's stuck on a weird build issue I don't understand.

**Comment by ussuri** [comment]
What's the build issue?

**Comment by xansec** [comment]
> I have a draft CL for this issue, but it's hung up on the riegeli dependency, which requires a very old version of protobuf. I'm attempting to update riegeli to use a newer protobuf, but it's stuck on a weird build issue I don't understand.

Not sure what issue you're having, but it looks like the latest riegeli was merged:
https://github.com/bazelbuild/bazel-central-registry/pull/1844

**Comment by tpudlik** [comment]
@wffurr could you share your draft CL? It would be great to see fuzztest in the BCR, and maybe the new riegeli version unblocks it!

**Comment by wffurr** [comment]
I haven't had a lot of time to work on this lately.  The new Riegeli does fix the protobuf version issue, but the e2e tests fail due to some sandboxing issue with bzlmod I don't understand.

https://github.com/google/fuzztest/pull/1174 is the PR.

**Comment by udaya2899** [comment]
I patched @wfurr 's work and made it work in cl/660832356. This should fix this long-standing issue.
